
- name: Remove eth1 config
  shell: sed -ie '/iface eth1/,+6d' /etc/network/interfaces
- name: Add "{{ br_vlan_name }}"
  shell: /sbin/brctl addbr "{{ br_vlan_name }}" || true
- name: Add "{{ br_vlan_name }}"  config file
  template: src="{{ br_vlan_name }}".cfg.j2 dest=/etc/network/interfaces.d/"{{ br_vlan_name }}".cfg
